// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SmartLab.Server;

#nullable disable

namespace SmartLab.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916193000_AlignOperationalModel")]
    partial class AlignOperationalModel
    {
    }
}
