// <auto-generated />
// Generated metadata companion for the AddMustChangePassword migration.
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;
using SmartLab.Server;

#nullable disable

namespace SmartLab.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917160000_AddMustChangePassword")]
    partial class AddMustChangePassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");
        }
    }
}
